routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BannersController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SettingController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/',[HomeController::class,'index']);
Route::group(['middleware'=>'auth'],function (){
    Route::resource('/app-banners',BannersController::class);
    Route::resource('/settings', SettingController::class);
});

require __DIR__.'/auth.php';

app/Models/AppBanner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AppBanner extends Model
{
    use HasFactory;
    protected $fillable = ['image','is_ban'];
}

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;
    protected $fillable = ['name','type','ar_value','en_value','page','slug','ar_title','en_title'];

    /**
     * @return mixed
     */
    public function getValueAttribute(){
        if(app()->getLocale() == 'ar')
            return $this->ar_value;
        return $this->en_value;
    }

    /**
     * @return mixed
     */
    public function getTitleAttribute(){
        if(app()->getLocale() == 'ar')
            return $this->ar_title;
        return $this->en_title;
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BannersController.php
<?php

namespace App\Http\Controllers;

use App\Models\AppBanner;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Validator;

class BannersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.app-banner.index',['banners'=>AppBanner::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.app-banner.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(),[
            'image'=>'required|image|mimes:jpeg,png,jpg|max:2048'
        ])->validate();
        $inputs['image'] = uploaderWithPath($request['image'],'banners');
        AppBanner::create($inputs);
        return redirect()->route('app-banners.index')->with('success','uploaded successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(AppBanner $app_banner)
    {
        return view('admin.app-banner.edit',compact('app_banner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  AppBanner $app_banner
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AppBanner $app_banner)
    {
        Validator::make($request->all(),[
            'image'=>'required|image|mimes:jpeg,png,jpg|max:2048'
        ])->validate();
        $inputs['image'] = uploaderWithPath($request['image'],'banners');
        $app_banner->update($inputs);
        return redirect()->route('app-banners.index')->with('success','uploaded successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  AppBanner $app_banner
     * @return \Illuminate\Http\Response
     */
    public function destroy(AppBanner $app_banner)
    {
        $app_banner->delete();
       return response()->json(['status'=>true,'message'=>'deleted successfully']);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\AppBanner;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(){
        $banners = AppBanner::where('is_ban',0)->get();
        return view('site.home.index',compact('banners'));
    }
}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Traits\SettingOperation;
use App\Models\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    use SettingOperation;

    public function __construct()
    {
        //
    }
    /**
     * Display a listing of the resource.
     *

     */
    public function index()
    {
        $pages = Setting::all()->pluck('slug')->unique();
        return view('admin.settings.index', compact('pages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     */
    public function store(Request $request)
    {
        $this->RegisterSetting($request);
        return redirect()->route('settings.index')->with('success', 'updated successfully');
    }


    public function show($id)
    {
        $settings = Setting::whereSlug($id)->get();
        $page = $id;
//        dd($settings[0]);
        return view('admin.settings.show', compact('settings', 'page'));
    }


}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/admin/alert.blade.php
<!-- This is an example component -->

@if(session('success'))
    <div class="container" id="alertbox">
    <div class="container bg-green-500 flex items-center text-white text-sm font-bold px-4 py-3 relative"
         role="alert">
        <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path
                d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z" />
        </svg>
        <p>{{session('success')}}</p>

        <span class="absolute top-0 bottom-0 right-0 px-4 py-3 closealertbutton">
				<svg class="fill-current h-6 w-6 text-white" role="button" xmlns="http://www.w3.org/2000/svg"
                     viewBox="0 0 20 20">
					<title>Close</title>
					<path
                        d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z" />
				</svg>
			</span>
    </div>
</div>
@endif

@if($errors->any())
    <div class="container" id="alertbox">
    <div class="container bg-red-500 flex items-center text-white text-sm font-bold px-4 py-3 relative" role="alert">
        <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path
                d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z" />
        </svg>

        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>

        <span class="absolute top-0 bottom-0 right-0 px-4 py-3 closealertbutton">
				<svg class="fill-current h-6 w-6 text-white" role="button" xmlns="http://www.w3.org/2000/svg"
                     viewBox="0 0 20 20">
					<title>Close</title>
					<path
                        d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z" />
				</svg>
			</span>
    </div>
</div>
@endif


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous">
</script>

<script>
    $(".closealertbutton").click(function (e) {
        // $('.alertbox')[0].hide()
        // e.preventDefault();
        pid = $(this).parent().parent().hide(500)
        console.log(pid)
        // $(".alertbox", this).hide()
    })
</script>

resources/views/admin/app-banner/create.blade.php
@extends('admin.app.layout')

@section('content')
    <div class="min-h-screen bg-gray-100">

        <!-- Page Heading -->
        <header class="bg-white shadow">
            <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
               <span class="max-w-xl">
                   <a href="{{route('dashboard')}}">Dashboard</a>
               </span>
               <span class="float-right ml-4 ">
                   <a href="{{route('app-banners.index')}}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">all banner</a>
               </span>
            </div>
        </header>

        <!-- Page Content -->
        <main>
            @include('admin.alert')
            <div class="container h-screen bg-gray-200 flex justify-center items-center">
{{--                <div class="bg-white h-96 w-80 rounded-2xl">--}}
                    {!! Form::open(['route' => 'app-banners.store','method'=>'post','class'=>'relative  mt-2 text-gray-900 p-2','files'=>true]) !!}
                        @include('admin.app-banner.form')
                        <div class="text-center mt-7">
                            <button type="submit" class="bg-black text-gray-50 px-3 py-2 rounded-2xl rounded-b-none">
                               save
                            </button>
                        </div>
                    {!! Form::close() !!}
{{--                </div>--}}
            </div>
        </main>
    </div>
@endsection

@section('scripts')
    <script>
        $('document').ready(function (){
            $('.image-uploader').change(function (event) {
                $(this).parents('.upload-container').find('.img-uploaded').attr('src',URL.createObjectURL(event.target.files[0]));
                    // .append('<div class="uploaded-block"><img src="' +  + '"><button class="close">&times;</button></div>');
            });
        })
    </script>
@endsection

resources/views/admin/app-banner/edit.blade.php
@extends('admin.app.layout')

@section('content')
    <div class="min-h-screen bg-gray-100">

        <!-- Page Heading -->
        <header class="bg-white shadow">
            <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
               <span class="max-w-xl">
                   <a href="{{route('dashboard')}}">Dashboard</a>
               </span>
               <span class="float-right ml-4 ">
                   <a href="{{route('app-banners.index')}}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">all banner</a>
               </span>
            </div>
        </header>

        <!-- Page Content -->
        <main>
            @include('admin.alert')
            <div class="container h-screen bg-gray-200 flex justify-center items-center">
{{--                <div class="bg-white h-96 w-80 rounded-2xl">--}}
                    {!! Form::model($app_banner,['route' => ['app-banners.update',$app_banner],'method'=>'put','class'=>'relative  mt-2 text-gray-900 p-2','files'=>true]) !!}
                        @include('admin.app-banner.form')
                        <div class="text-center mt-7">
                            <button type="submit" class="bg-black text-gray-50 px-3 py-2 rounded-2xl rounded-b-none">
                               save
                            </button>
                        </div>
                    {!! Form::close() !!}
{{--                </div>--}}
            </div>
        </main>
    </div>
@endsection

@section('scripts')
    <script>
        $('document').ready(function (){
            $('.image-uploader').change(function (event) {
                $(this).parents('.upload-container').find('.img-uploaded').attr('src',URL.createObjectURL(event.target.files[0]));
                    // .append('<div class="uploaded-block"><img src="' +  + '"><button class="close">&times;</button></div>');
            });
        })
    </script>
@endsection

resources/views/admin/app-banner/form.blade.php
<div class="py-3 center mx-auto">
    <div class="bg-white px-4 py-5 rounded-lg shadow-lg text-center w-48 upload-container">
        <div class="mb-4">
            <img class="w-auto mx-auto rounded-full object-cover object-center img-uploaded"
                 src="{{isset($app_banner)?checkHasImage($app_banner):'https://i1.pngguru.com/preview/137/834/449/cartoon-cartoon-character-avatar-drawing-film-ecommerce-facial-expression-png-clipart.jpg'}}" alt="Avatar Upload" />
        </div>
        <label class="cursor-pointer mt-6">
            <span class="mt-2 text-base leading-normal px-4 py-2 bg-blue-500 text-white text-sm rounded-full" >Select Image</span>
            <input type='file'  name="image" class="hidden image-uploader" />
        </label>
    </div>
</div>

resources/views/admin/app-banner/index.blade.php
@extends('admin.app.layout')

@section('content')
    <div class="min-h-screen bg-gray-100">

        <!-- Page Heading -->
        <header class="bg-white shadow">
            <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
               <span class="max-w-xl">
                   <a href="{{route('dashboard')}}">Dashboard</a>
               </span>
               <span class="float-right ml-4 ">
                   <a href="{{route('app-banners.create')}}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">add banner</a>
               </span>
            </div>
        </header>

        <!-- Page Content -->
        <main>
           @include('admin.alert')
            <div class="overflow-x-auto">
                <div class="min-w-screen min-h-screen bg-gray-100 flex items-center justify-center bg-gray-100 font-sans overflow-hidden">
                    <div class="w-full lg:w-5/6">
                        <div class="bg-white shadow-md rounded my-6">

                            <table class="min-w-max w-full table-auto">
                                <thead>
                                <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                                    <th class="py-3 px-6 text-left">ID</th>
                                    <th class="py-3 px-6 text-left">Image</th>
                                    <th class="py-3 px-6 text-center">Status</th>
                                    <th class="py-3 px-6 text-center">Actions</th>
                                </tr>
                                </thead>
                                <tbody class="text-gray-600 text-sm font-light">
                                    @foreach($banners as $banner)
                                        <tr class="border-b border-gray-200 bg-gray-50 hover:bg-gray-100" id="el-{{$banner->id}}">
                                            <td class="py-3 px-6 text-left">
                                                <div class="flex items-center">
                                                    <span class="font-medium">{{$banner->id}}</span>
                                                </div>
                                            </td>
                                            <td class="py-3 px-6 text-left">
                                                <div class="flex items-center">
                                                    <div class="mr-2">
                                                        <img class="w-16 h-16 rounded-full" src="{{getImg($banner->image)}}"/>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="py-3 px-6 text-center">
                                                <span class="{{($banner->is_ban)?'bg-yellow-200':'bg-green-200'}} text-black-200 py-1 px-3 rounded-full text-xs">{{($banner->is_ban)?'in active':'active'}}</span>
                                            </td>
                                            <td class="py-3 px-6 text-center">
                                                <div class="flex item-center justify-center">
                                                    <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                        <a href="{{route('app-banners.edit',$banner)}}">
                                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                                            </svg>
                                                        </a>

                                                    </div>

                                                    <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110" onclick="confirmDelete({{$banner->id}})">
                                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                        </svg>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
@endsection

@section('scripts')
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        function confirmDelete(id) {
            var result = confirm("Want to delete?");
            if (result) {
                var url = `app-banners/${id}`;
                $.ajax({
                    url,
                    method: "Delete",
                    success:(response)=>{
                        $(`#el-${id}`).remove();
                        // alert(response.message);
                    },
                    error:(error)=>{
                        console.log(error);
                    }
                });
            }
        }

    </script>
@endsection

resources/views/admin/app/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('page-title')</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">
    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    @yield('styles')
</head>
<body class="font-sans antialiased">
@yield('content')
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
@yield('scripts')
</body>
</html>

resources/views/admin/settings/show.blade.php
@extends('admin.app.layout')

@section('content')
    <div class="min-h-screen bg-gray-100">

        <!-- Page Heading -->
        <header class="bg-white shadow">
            <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
               <span class="max-w-xl">
                   <a href="{{route('dashboard')}}">Dashboard</a>
               </span>
               <span class="float-right ml-4 ">
                   <a href="{{route('settings.index')}}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">all settings</a>
               </span>
            </div>
        </header>

        <!-- Page Content -->
        <main>
           @include('admin.alert')
           <!-- component -->
               <div class="py-12">
                   <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                       <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                           <div class="p-6 bg-white border-b border-gray-200">
                               <form method="POST" action="{{route('settings.store')}}">
                                   @csrf
                                   @foreach($settings as $setting)
                                   @if($setting->type == 'text')
                                       <div class="mb-4">
                                           <label class="text-xl text-gray-600">Ar {{$setting->title}} <span class="text-red-500">*</span></label></br>
                                           <input type="text" class="border-2 border-gray-300 p-2 w-full" name="{{$setting->name.'[]'}}" id="title" value="{{($setting->ar_value)}}" required>
                                       </div>

                                       <div class="mb-4">
                                           <label class="text-xl text-gray-600">En  {{$setting->title}} <span class="text-red-500">*</span></label></br>
                                           <input type="text" class="border-2 border-gray-300 p-2 w-full" name="{{$setting->name.'[]'}}" id="title" value="{{($setting->en_value)}}" required>
                                       </div>
                                   @endif
                                   @if($setting->type == 'number')
                                       <div class="mb-4">
                                           <label class="text-xl text-gray-600">{{$setting->title}}  <span class="text-red-500">*</span></label></br>
                                           <input type="number" class="border-2 border-gray-300 p-2 w-full" name="{{$setting->name}}" id="title" value="{{($setting->value)}}" required>
                                       </div>
                                   @endif
                                   @if($setting->type == 'email')
                                       <div class="mb-4">
                                           <label class="text-xl text-gray-600">{{$setting->title}}  <span class="text-red-500">*</span></label></br>
                                           <input type="email" class="border-2 border-gray-300 p-2 w-full" name="{{$setting->name}}" id="title" value="{{($setting->value)}}" required>
                                       </div>
                                   @endif
                                   @if($setting->type == 'url')
                                       <div class="mb-4">
                                           <label class="text-xl text-gray-600">{{$setting->title}} Link  <span class="text-red-500">*</span></label></br>
                                           <input type="text" class="border-2 border-gray-300 p-2 w-full" name="{{$setting->name}}" id="title" value="{{($setting->value)}}" required>
                                       </div>
                                   @endif
                                   @if($setting->type == 'long_text')
                                       <div class="mb-8">
                                           <label class="text-xl text-gray-600">Ar {{$setting->title}} <span class="text-red-500">*</span></label></br>
                                           <textarea name="{{$setting->name.'[]'}}" class="border-2 border-gray-500 editor">{{$setting->ar_value}}</textarea>
                                       </div>

                                       <div class="mb-8">
                                           <label class="text-xl text-gray-600">En {{$setting->title}} <span class="text-red-500">*</span></label></br>
                                           <textarea name="{{$setting->name.'[]'}}" class="border-2 border-gray-500 editor">{{$setting->en_value}}</textarea>
                                       </div>
                                   @endif
                                   @endforeach
                                   <div class="flex p-1">
                                       <button role="submit" class="p-3 bg-blue-500 text-white hover:bg-blue-400" required>Submit</button>
                                   </div>
                               </form>
                           </div>
                       </div>
                   </div>
               </div>
        </main>
    </div>
@endsection

@section('scripts')
    <script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>

    <script>
        CKEDITOR.replaceAll( 'editor' );
    </script>
@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/site/home/index.blade.php
@extends('site.app.layout')

@section('content')

@include('site.home.about-sec')
@include('site.home.our-steps-sec')
@include('site.home.utility-sec')
@include('site.home.app-banners-sec')
@include('site.home.contact-sec')





@endsection